package ua.tqs.homework.selenium;

// Generated by Selenium IDE
import org.junit.jupiter.api.extension.ExtendWith;

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

import io.github.bonigarcia.seljup.SeleniumJupiter;
import io.github.bonigarcia.wdm.WebDriverManager;

@ExtendWith(SeleniumJupiter.class)
public class BuyBusTripWebDriverTest {
  
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
		driver = new ChromeDriver();

    // driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testbuybustrip(ChromeDriver driver) {
    // Test name: Untitled
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:9091/");
    // 2 | setWindowSize | 1083x694 | 
    driver.manage().window().setSize(new Dimension(1083, 694));
    // 3 | click | id=from-input | 
    driver.findElement(By.id("from-input")).click();
    // 4 | type | id=from-input | Aveiro
    driver.findElement(By.id("from-input")).sendKeys("Aveiro");
    // 5 | click | id=to-input | 
    driver.findElement(By.id("to-input")).click();
    // 6 | type | id=to-input | Viseu
    driver.findElement(By.id("to-input")).sendKeys("Viseu");
    // 7 | click | css=.form-control:nth-child(3) | 
    driver.findElement(By.cssSelector(".form-control:nth-child(3)")).click();
    // 8 | type | css=.form-control:nth-child(3) | 2024-04-09
    driver.findElement(By.cssSelector(".form-control:nth-child(3)")).sendKeys("2024-04-09");
    // 9 | click | css=.form-select | 
    driver.findElement(By.cssSelector(".form-select")).click();
    // 10 | select | css=.form-select | label=1
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".form-select"));
      dropdown.findElement(By.xpath("//option[. = '1']")).click();
    }
    // 11 | click | css=option:nth-child(2) | 
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    // 12 | click | id=search-trip-btn | 
    driver.findElement(By.id("search-trip-btn")).click();
    // 13 | click | css=tr:nth-child(3) .btn | 
    driver.findElement(By.cssSelector("tr:nth-child(3) .btn")).click();
    // 14 | assertAlert | Bus Trip Booked: 3 | 
    assertThat(driver.switchTo().alert().getText(), is("Bus Trip Booked: 3"));
    // 15 | click | css=.form-control:nth-child(2) | 
    driver.findElement(By.cssSelector(".form-control:nth-child(2)")).click();
    // 16 | type | css=.form-control:nth-child(2) | MR
    driver.findElement(By.cssSelector(".form-control:nth-child(2)")).sendKeys("MR");
    // 17 | click | css=.form-control:nth-child(4) | 
    driver.findElement(By.cssSelector(".form-control:nth-child(4)")).click();
    // 18 | type | css=.form-control:nth-child(4) | 20
    driver.findElement(By.cssSelector(".form-control:nth-child(4)")).sendKeys("20");
    // 19 | click | css=.form-control:nth-child(6) | 
    driver.findElement(By.cssSelector(".form-control:nth-child(6)")).click();
    // 20 | type | css=.form-control:nth-child(6) | Street Eça, 123
    driver.findElement(By.cssSelector(".form-control:nth-child(6)")).sendKeys("Street Eça, 123");
    // 21 | click | css=.form-control:nth-child(8) | 
    driver.findElement(By.cssSelector(".form-control:nth-child(8)")).click();
    // 22 | type | css=.form-control:nth-child(8) | Aveiro
    driver.findElement(By.cssSelector(".form-control:nth-child(8)")).sendKeys("Aveiro");
    // 23 | click | css=.form-control:nth-child(10) | 
    driver.findElement(By.cssSelector(".form-control:nth-child(10)")).click();
    // 24 | type | css=.form-control:nth-child(10) | Aveiro
    driver.findElement(By.cssSelector(".form-control:nth-child(10)")).sendKeys("Aveiro");
    // 25 | click | css=.form-control:nth-child(12) | 
    driver.findElement(By.cssSelector(".form-control:nth-child(12)")).click();
    // 26 | type | css=.form-control:nth-child(12) | 1234-678
    driver.findElement(By.cssSelector(".form-control:nth-child(12)")).sendKeys("1234-678");
    // 27 | click | css=.form-control:nth-child(19) | 
    driver.findElement(By.cssSelector(".form-control:nth-child(19)")).click();
    // 28 | type | css=.form-control:nth-child(19) | 34589
    driver.findElement(By.cssSelector(".form-control:nth-child(19)")).sendKeys("34589");
    // 29 | click | css=.col-sm-5:nth-child(2) > .form-control | 
    driver.findElement(By.cssSelector(".col-sm-5:nth-child(2) > .form-control")).click();
    // 30 | type | css=.col-sm-5:nth-child(2) > .form-control | 03
    driver.findElement(By.cssSelector(".col-sm-5:nth-child(2) > .form-control")).sendKeys("03");
    // 31 | click | css=.col-sm-5:nth-child(3) > .form-control | 
    driver.findElement(By.cssSelector(".col-sm-5:nth-child(3) > .form-control")).click();
    // 32 | type | css=.col-sm-5:nth-child(3) > .form-control | 2027
    driver.findElement(By.cssSelector(".col-sm-5:nth-child(3) > .form-control")).sendKeys("2027");
    // 33 | click | css=.form-control:nth-child(22) | 
    driver.findElement(By.cssSelector(".form-control:nth-child(22)")).click();
    // 34 | type | css=.form-control:nth-child(22) | MR
    driver.findElement(By.cssSelector(".form-control:nth-child(22)")).sendKeys("MR");
    // 35 | click | id=search-trip-btn | 
    driver.findElement(By.id("search-trip-btn")).click();
  }
}

